### PR TITLE
Add support for .bin pack

### LINKED ISSUE #209: Plugin Request [pack]
**Game Name:**  Subarashiki Kono Sekai
**Console:**  NDS
**Format extension(s):**  .bin
**Type:** archive

**First 8 or more bytes of the file(s):**
70 61 63 6B 48 00 00 00

**More details:**
Header:
0x00: 7061636B (pack) magic
0x04: File count
0x08: Size of files in the archive
0x0C: Padding (20 bytes)

Table:
0x20: File1 offset + header size (0x20)
0x24: File1 size
0x28: File2 offset + header size (0x20)
0x2C: File2 size
etc

Every file size is multiple of 32 bytes.

**Sample files (if possible):**
[https://www.mediafire.com/file/i9esemhe4bxhzux](https://www.mediafire.com/file/i9esemhe4bxhzux)

### PR DESCRIPTION
**Pull request by caleb-mabry**
Looking to resolve #209

### CODE REVIEW

**Comment by caleb-mabry** [comment]
Seems like my branches got crossed a little

**Comment by caleb-mabry** [comment]
This should be ready for review.
You can extract files and replace files with no issues. If there's anything else I should update, please let me know!

**Comment by IcySon55** [comment]
Perhaps Bin is too generic a name for this plugin. What are the common characters in the header? I see it has a 4 byte string in the header.

**Comment by caleb-mabry** [comment]
Closing this as it's been open for so long and I don't plan on returning.

**Pull request closed without merging**
