### PR TITLE
Update plugin-request.md

### PR DESCRIPTION
**Pull request by HoldYourWaffle**
I made 'section headers' bold, which makes issues more readable in my opinion.
I also made the "don't attach" message a comment, instead of having to delete it.

### CODE REVIEW

**Comment by onepiecefreak3** [comment]
In the future please only create PR's to dev. Future PR's to master will be declined.
This was an exception since it proofs helpful but does not update any source code and cannot introduce any errors.

**Comment by HoldYourWaffle** [comment]
Woops, will do!

You should probably mention this in a `CONTRIBUTING.md` file or something similar, as far as I can tell there's no way I could've known this.

**Comment by onepiecefreak3** [comment]
That is right. That is why I accepted the PR. It would have also been unfair for you, and since I couldn't contact you otherwise, I just accepted it. The project is still trying to get everything figured out for contributors and developers to work as smooth as possible. You're welcome to give further hints, help, or contributions to the code base if you can.

**Comment by HoldYourWaffle** [comment]
Perhaps it'd be a good idea to change the default branch to `dev`?
When opening #80 I almost left `master` again (I suppose out of habit 😅).

**Pull request merged**
