### PR TITLE
Combine RGBA channels of level5 xf font image

### PR DESCRIPTION
**Pull request by LITTOMA**
Calling Graphics.DrawImage with a ColorMatrix doesn't output a combined image. It only gives you an image of a single channel.

### CODE REVIEW

**Comment by onepiecefreak3** [comment]
The code is already confirmed working. The images get combined without a problem.
Did you encounter an issue with the existing code that made you believe it didn't work?

**Comment by onepiecefreak3** [comment]
I will test the code again tonight, just to make sure this "still" holds true.

**Comment by LITTOMA** [comment]
@onepiecefreak3 see #100

**Comment by LITTOMA** [comment]
I use .NET 5 to run this code. Would it be the problem?

**Comment by onepiecefreak3** [comment]
I commenced my tests and you are right, that the images always get replaced, instead of merged together correctly. This fact was not apparent in the current use cases, since the created character sets always occupied only one channel.

**Comment by onepiecefreak3** [comment]
However, I dislike the use of marshal copy. It is unnecessary to copy the buffers just to work on them. Since you lock the bitmaps already, you can work on the buffer itself. Please change that and the PR can be merged.

**Comment by LITTOMA** [comment]
Make sense. 
Changed.

**Comment by LITTOMA** [comment]
Oops, sorry, I closed to PR accidently.

**Pull request merged**
